### ISSUE TITLE
Compression de l'image trop agressive

### ISSUE THREAD

**Issue by phil-roy** [shenault/mhack#116]
Trouver un juste milieu de compression vs qualité de l'image.

**Comment by mquirion77** [comment]
Le niveau de compression est un problème mais il faut aussi détecter la taille d'origine car actuellement, toutes les images terminent avec une taille de 280 x 280. Ce qui n'aide pas à la qualité finale. 

Il faudra conserver le ratio d'origine et possiblement garder l'image avec son côté le plus petit à 500px.

**Comment by phil-roy** [comment]
https://collaboratiohack.firebaseapp.com
